################################# Default configuration ###################
baseURL = "https://www.paul-gerhart.de"
title = "Paul Gerhart"
theme = "Freiberuf"
# disable language
disableLanguages = []

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "About"
url = "/#about"
weight = 1

[[Languages.en.menu.main]]
name = "Publications"
url = "/publications"
weight = 3

[[Languages.en.menu.main]]
name = "Teaching"
url = "/#teaching"
weight = 4

[[Languages.en.menu.main]]
name = "Community Service"
url = "/#commservice"
weight = 5

[[Languages.en.menu.main]]
name = "Imprint"
url = "imprint"
weight = 11 

############################# Default Parameters ##########################
[params]
logo = "images/logo/PGLogoHighContrast.svg"
author = "Paul Gerhart"
title = "Paul Gerhart"
ustid = ""


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2022 Paul Gerhart"

